### ISSUE TITLE
incorrect markdown format

### ISSUE THREAD

**Issue by youyu16** [feich-ms/test_github_assistant_repo#6]
line3 syntax is not right, could you please fix it.

**Comment by feich-ms** [comment]
@cosmicshuai  could you take a fix?

**Comment by feich-ms** [comment]
@cosmicshuai could you take a fix?

**Comment by feich-ms** [comment]
@cosmicshuai could you take a fix

**Comment by feich-ms** [comment]
@cosmicshuai could you take a fix?
